language: csharp

sudo: false

services:
  - docker

before_script:
 - chmod +x build.sh

script:
 - ./build.sh BuildApp "$READABILITY_AUTHENTICATION_TOKEN"

after_success:
 - docker build -t mveith/webtoepub .
 - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" -e="$DOCKER_EMAIL"
 - docker push mveith/webtoepub
